// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbThxpnPLqR_dmYY03R0Ic9AgP188ITeA',
    appId: '1:770570200465:web:fea3415f43147115f4e630',
    messagingSenderId: '770570200465',
    projectId: 'helpwanted-a26a3',
    authDomain: 'helpwanted-a26a3.firebaseapp.com',
    storageBucket: 'helpwanted-a26a3.firebasestorage.app',
    measurementId: 'G-FQMNRJRLX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5tiWSI-Ik-JKbBYxplNvlNxABw41nMU',
    appId: '1:770570200465:android:4fceb7ec55bd5603f4e630',
    messagingSenderId: '770570200465',
    projectId: 'helpwanted-a26a3',
    storageBucket: 'helpwanted-a26a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7igm22MCgnMQVMkySnQXP6oQ8RSLUfvI',
    appId: '1:770570200465:ios:43b48c3929161a27f4e630',
    messagingSenderId: '770570200465',
    projectId: 'helpwanted-a26a3',
    storageBucket: 'helpwanted-a26a3.firebasestorage.app',
    iosBundleId: 'com.example.helpwanted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7igm22MCgnMQVMkySnQXP6oQ8RSLUfvI',
    appId: '1:770570200465:ios:43b48c3929161a27f4e630',
    messagingSenderId: '770570200465',
    projectId: 'helpwanted-a26a3',
    storageBucket: 'helpwanted-a26a3.firebasestorage.app',
    iosBundleId: 'com.example.helpwanted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbThxpnPLqR_dmYY03R0Ic9AgP188ITeA',
    appId: '1:770570200465:web:59fb185bf742d25ff4e630',
    messagingSenderId: '770570200465',
    projectId: 'helpwanted-a26a3',
    authDomain: 'helpwanted-a26a3.firebaseapp.com',
    storageBucket: 'helpwanted-a26a3.firebasestorage.app',
    measurementId: 'G-MG637PMST2',
  );
}
